apiVersion: apps/v1
kind: Deployment
metadata:
    name: nest-example
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nest
    template:
        metadata:
            labels:
                app: nest
        spec:
            containers:
                - name: nest
                  image: nohns/nest-example
                  ports:
                    - containerPort: 3234