apiVersion: v1
kind: Service
metadata:
  name: nest-example
  namespace: nest-example
spec:
  selector:
    app: nest-example
  ports:
  - port: 80
    targetPort: 3234
    nodePort: 30080
  type: NodePort
